### ISSUE TITLE
macOS Catalina only? Why?

### ISSUE THREAD

**Issue by strafer** [Sh1d0w/clean-links#1]
Is there a technical reason why this isn't compatible with macOS Mojave and earlier, especially considering what a garbage fire Catalina is?

Would love to have this on Mojave if possible.

**Comment by Sh1d0w** [comment]
That's one very good point. This is a Safari App Extension and according to Apple, it should be supported:

```
Safari app extensions are available in macOS 10.12 and later, and in OS X 10.11.5 with Safari 10 installed.
```

I've changed the deployment target to 10.12 and published new release. Let me know if you find any problems with it.
