### ISSUE TITLE
Link opened in new window instead of in new tab on Safari 14.0.3 and Big Sur (11.2.1)

### ISSUE THREAD

**Issue by HakureiKion** [Sh1d0w/clean-links#11]
## Encountered problem
With "Open each selected result in a new browser window" enabled in "Tools > Search settings" on Google, the left-clicked search result is always opened in a new Safari window.

## Expected behavior
The search result should be opened in a new tab instead of a new window.

## Additional information
Despite the option description containing "new browser window", the results are opened in a new tab with the extension not installed or disabled. Therefore, results opened in new tabs should be the normal behavior.

## Other attempts
With the open-in-new-window option disabled, the extension works fine: the results are opened in the same tab when left-clicked, in a new tab when middle-clicked or ⌘-left-clicked. 
With the option enabled, the results are only opened in a new tab when middle-clicked or ⌘-left-clicked. Left-clicks brings up a new window, like mentioned in the encountered problem.

Also, thank you for developing this extension! :)

**Comment by Sh1d0w** [comment]
Hey there @HakureiKion , sorry for the late replay, been some very busy months for me.

Can you see what you have selected for this option:

<img width="904" alt="Screenshot 2021-06-23 at 9 01 44" src="https://user-images.githubusercontent.com/5074917/123044012-caf45c80-d401-11eb-9814-274e7dac89e6.png">

It should be "Always" not "Automatically" or "Never". Cheers.
