### ISSUE TITLE
Middle click

### ISSUE THREAD

**Issue by poweruser82** [Sh1d0w/clean-links#2]
It would be possible to add support for middle click? I.e. to open links in new tab when clicking with the middle button of the mouse.
Now if I middle click on a Google search result, it open in the same tab instead of a new one.
TIA

**Comment by Sh1d0w** [comment]
That sounds reasonable. I've just made a new release which should make this possible - https://github.com/Sh1d0w/clean-links/releases/tag/v1.2%2B7

Thanks!

**Comment by eramdam** [comment]
Sorry for bumping an old issue but I'm seeing the issue with the latest version of the extension with Safari 14.0.2 on Big Sur 11.1 😕
