### ISSUE TITLE
Any plans for an iOS Safari Extension too?

### ISSUE THREAD

**Issue by shaunkoh** [Sh1d0w/clean-links#22]
Apologies if this isn’t the right place to ask this!

**Comment by Sh1d0w** [comment]
That's a reasonable request, however currently I don't have the time. Any PR's are welcome!

**Comment by georgesmaragdakis** [comment]
@Sh1d0w any updates? I do most of my Googling on iOS and I'm sure this is true for most people. An iOS/iPadOS extension would be wonderful.
