### ISSUE TITLE
Option to remove Extension icon and/or counter from Safari toolbar

### ISSUE THREAD

**Issue by StreborStrebor** [Sh1d0w/clean-links#26]
Great little extension that does exactly what I installed it for:
Removing Google Search links Redirection Notice (Nice when running Google Chat in Electron wrapper, which sends links as google search links to Safari).

However, It would be great if there was the option to not show the extension Icon with the counter on my Safari toolbar.

PS. Bought you coffee

**Comment by Sh1d0w** [comment]
Hi @StreborStrebor , thanks for the support! I am glad the extension is useful to you.

What you are asking is built in in Safari, you can add/remove items in from the toolbar. I am attaching a video how you can do it


https://user-images.githubusercontent.com/5074917/199728708-e039c7d1-d4af-460a-803a-41e5dc448c7c.mov

Cheers!

**Comment by StreborStrebor** [comment]
Thanks! Case closed!
