### ISSUE TITLE
Typo: mscklid should be msclkid

### ISSUE THREAD

**Issue by xta** [Sh1d0w/clean-links#7]
In your list, you have "mscklid"

MS has it as "msclkid".

> When you enable auto-tagging of the Microsoft Click ID, it allows Bing Ads to automatically add a unique click ID to the landing page URL after a customer clicks your ad. The landing page URL may look something like this: www.contoso.com/?msclkid=123abc.

Via https://about.ads.microsoft.com/en-us/blog/post/january-2018/conversion-tracking-update-on-bing-ads

**Comment by Sh1d0w** [comment]
Thanks!
